### ISSUE TITLE
Updated compile?

### ISSUE THREAD

**Issue by tsheeley** [nxminens/nxminens#10]
First off... I love this project! I use it on my home network with the official BDS to run our own local Realms and PocketMine to allow access to non-Featured Servers. I'm constantly recommending it to folks on Reddit.

I see you merged in some updates to the Featured Servers that get forwarded... but I'm not seeing a new compile? 

Do I need to compile it myself? If so, is there a tool you could recommend to do it?

Thanks!

**Comment by mitchellurgero** [comment]
I can probably recompile, or rewrite it to work with a list of servers instead externally so you can just add your own list?

**Comment by mitchellurgero** [comment]
I'm so happy there are people out there enjoying this project - Binaries updated: https://github.com/nxminens/nxminens/releases/tag/0.0.2

**Comment by tsheeley** [comment]
Awesome! Thank you!!!
