### ISSUE TITLE
problems running nxminens on a Ubuntu Server 20.04.

### ISSUE THREAD

**Issue by Sacki666** [nxminens/nxminens#11]
Hi there,
I've problems running nxminens on a new Ubuntu Server 20.04.

I've downloaded the latest version and tryed to run in, the result is allways:

msack@sackmine4:~/nxminens$ dotnet ./NXMineNS 192.168.1.94
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/msack/nxminens/NXMineNS does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
 
dotnet info:
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.816 [/usr/share/dotnet/sdk]
  5.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mitchellurgero** [comment]
When you extract the zip file on linux, make sure to *all* the files are in the same folder. Then cd into the folder. Inside there you will see a build that will error out cause DNS.DLL is missing from the system - that's fine, just cd into publish folder and run inside there instead:

EX: `cd linux-x64\publish && chmod +x NXMineNS && sudo ./NXMineNS 192.168.1.94`

Not sure why the linux build does this (New to .net core tbh) but this works without issue.

**Comment by Sacki666** [comment]
Hi,
thanks, that works fine. Maybe you should change the "Instructions for Linux" in the second point, that the "dotnet" is not needed anymore and that the program should run with root rights.

Thanks for the program and the suppot!
