### ISSUE TITLE
NXMineNS.deps.json was not found

### ISSUE THREAD

**Issue by ghost** [nxminens/nxminens#12]
Hi, I have Microsoft .NET Core SDK 2.1.817 (x64) installed and I'm getting this error

C:\Users\RevolverTexture\Desktop\NXMineNS>NXMineNS.exe 6DEGNi.mymcserver.org
Error:
  An assembly specified in the application dependencies manifest (NXMineNS.deps.json) was not found:
    package: 'DNS', version: '5.0.0'
    path: 'lib/netstandard2.0/DNS.dll'

I also tried using dotnet restore just like in the issue#2 but it didn't worked
I'm using command prompt as a administrator on Windows 10

**Comment by mitchellurgero** [comment]
I think it's a weird build bug I need to work out, run the exe in `C:\Users\RevolverTexture\Desktop\NXMineNS\publish\`

**Comment by ghost** [comment]
Thanks, it worked!
