### ISSUE TITLE
Missing dependencies error

### ISSUE THREAD

**Issue by Shabbypenguin** [nxminens/nxminens#2]
NXMineNS.exe 192.168.1.195
Error:
  An assembly specified in the application dependencies manifest (NXMineNS.deps.json) was not found:
    package: 'DNS', version: '5.0.0'
    path: 'lib/netstandard2.0/DNS.dll'

.netcore 2.2 is installed

**Comment by mitchellurgero** [comment]
Try running `dotnet restore` or `dotnet.exe restore` in the directory you extracted the release to. If that works I'll add the instructions to it.

**Comment by Shabbypenguin** [comment]
`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

however, grabbing the entire source and compiling it myself worked fine 


```
nxminens-master\NXMineNS\bin\Release\netcoreapp2.1> dotnet.exe .\NXMineNS.dll
NXMineNS - Version 0.0.1
    Usage: nxminens 192.168.1.4
    Replace 192.168.1.4 with your Minecraft Bedrock Server IP.
```

running the dll and exe from your releases page with dotnet.exe results in same dns.dll error missing.

**Comment by mitchellurgero** [comment]
This is my first .NET Core project, I'll look into how to properly do a release and will update the repo. Thanks for the feed back!

**Comment by Shabbypenguin** [comment]
https://www.diffchecker.com/yn7XKfJN

this is a diff of releases dependencies.json on the right and source built on the left. i compiled using VS2019 and set to Any vs x64. Hope you are able to figure it out, thank you for your work.

**Comment by mitchellurgero** [comment]
So for the release here in GitHub, the files can be ran from the publish folder (after extracting) so try that.

**Comment by Shabbypenguin** [comment]
Yea that works.

**Comment by mitchellurgero** [comment]
Alright - then I just packaged it wrong. WIll re-release when I can

**Comment by mitchellurgero** [comment]
Release 0.0.1 rebuilt and re-released, give it a shot if you want.

**Comment by Shabbypenguin** [comment]
Works great.

**Comment by mitchellurgero** [comment]
Alright, I'll go ahead and close this issue then, thank you again for the feedback!
