### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by dmitryistomin** [nxminens/nxminens#4]
After starting the script returns it. switch can not connect to my DNS

Looks like we are all set. Set your Switch's DNS to the IP of this computer!
Address already in use

**Comment by mitchellurgero** [comment]
If you have port 53 in use, this will not work. You will need to use a different computer that doesn't have that port in use or stop the service that is using that port.

**Comment by dmitryistomin** [comment]
I have a freshly installed ubuntu 18.04. All I managed to do on it is run a bedrock server and script

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      261/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      488/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      488/sshd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           261/systemd-resolve
udp        0      0 0.0.0.0:19132           0.0.0.0:*                           509/bedrock_server
udp6       0      0 :::19133                :::*                                509/bedrock_server

**Comment by mitchellurgero** [comment]
What is the output of:

`netstat -anop`

(Please using the code braces for the output "```" at the top and bottom of the text.)

**Comment by dmitryistomin** [comment]
https://gist.github.com/dmidex/1aab6f367b31e3b550de9ea67a26fda3

**Comment by mitchellurgero** [comment]
According to the output of the command, the "resolver" daemon is taking port 53. Follow the answer here to disable it to use this application:

https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

**Comment by dmitryistomin** [comment]
Finally it works, thank you
