### ISSUE TITLE
Configuration for online

### ISSUE THREAD

**Issue by davidf03** [nxminens/nxminens#9]
Hi, I managed to get this to work for my local network, but my ultimate goal is to connect with my friends.
Is it possible to configure the project to work like this?
I've been trying all day and haven't made any progress with this, but admittedly I'm way out of my depth, so I thought I'd finally just ask.
Thanks

**Comment by mitchellurgero** [comment]
What you will need to do is port forward for your server like normal on your router and have your friend use nxminens to then connect to your external IP.

**Comment by mitchellurgero** [comment]
Please also keep in mind that this application is just a DNS server it does not handle the connection to minecraft beyond telling your switch where to go. That's it.

**Comment by davidf03** [comment]
Yeah, that's exactly how I understood it, so that's great. I guess my problems lie elsewhere. For some reason not even setting the DMZ on my router allows canyouseeme.org to see that the port is open, even with windows and router firewalls off.
But anyway I'm trying to test it; would I be able to use my own machine to do this? As in have nxminens connect to the external ip of machine it's running on?
Thanks

**Comment by mitchellurgero** [comment]
Yeah nxminens will redirect to any IP you give it. Like I said it doesn't handle server connections, it only tells the switch where to look for the servers.

**Comment by davidf03** [comment]
Awesome, I really appreciate all the guidance, thanks
